#!/usr/bin/env node
import { colors } from './index'

// console.log(colors);

const generateTableRow = (name: string, hex: string) => {
  return `| ${name} | ![](https://via.placeholder.com/15/${hex}/000000?text=+) ${hex}  |`
}

const res = `
<!-- DO NOT EDIT THIS FILE! This is autogenerated -->
| Name | Color |
${Object.entries(colors).map(([name, hex]) => generateTableRow(name, hex)).join('\n')}`

console.log(res)
